---
# Сначала запускаем установку K3s как отдельный сценарий
- import_playbook: ansible/install_k3s.yml

# А теперь основной сценарий для деплоя инфраструктуры
- name: Infrastructure and App Deployment
  hosts: nodes
  become: yes
  tasks:
    - name: Fetch KUBECONFIG to Lenovo
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ./terraform/k3s.yaml
        flat: yes

    - name: Prepare KUBECONFIG for remote access
      delegate_to: localhost
      become: no
      replace:
        path: ./terraform/k3s.yaml
        regexp: '127.0.0.1'
        replace: "{{ ansible_host }}"

    - name: Run Terraform Apply
      delegate_to: localhost
      become: no
      environment:
        KUBECONFIG: "./terraform/k3s.yaml"
        TF_VAR_db_user: "{{ lookup('env', 'DB_USER') }}"
        TF_VAR_db_password: "{{ lookup('env', 'DB_PASS') }}"
        # Указываем Terraform использовать наш конфиг зеркала
        TF_CLI_CONFIG_FILE: "$GITHUB_WORKSPACE/terraform/.terraformrc"
      shell: |
        cd terraform
        # Полная очистка перед стартом
        rm -rf .terraform .terraform.lock.hcl
        # Инициализация через зеркало
        terraform init -input=false
        terraform apply -auto-approve