---
# 1 глобалки сценария
- name: Install K3s on the worker node
  hosts: nodes              # берет список серверов из hosts.ini
  become: yes               # всё от root (как sudo)

  tasks:
    # 2 подготовка системы
    - name: Update apt cache
      apt:
        update_cache: yes   # типа 'sudo apt update'

    # 3 доставка бинарника
    #- name: Copy k3s binary from Lenovo to Server

     # copy:
      #  src: ./k3s
       # dest: /usr/local/bin/k3s
        #mode: '0755'

    # 4 основная установка
   # - name: Run K3s installer script

    #  shell: curl -sfL https://get.k3s.io | INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_EXEC="--tls-san {{ ansible_host }}" sh - # k3s уже есть лупи скрипт
      
      # Параметр 'creates' делает сценарий "идемпотентным":
      # Если файл службы k3s уже создан, Ansible поймет, что всё готово, и пропустит шаг.
     # args:
      #  creates: /etc/systemd/system/k3s.service
    - name: Install k3s via script
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s
    # 5. Проверка жизнеспособности
    - name: Wait for node to be ready
      # Просим K3s показать статус нод
      shell: k3s kubectl get nodes
      register: nodes_output     # Сохраняем ответ команды в переменную
      
      # Цикл: повторяем команду, пока в выводе не появится слово "Ready"
      until: '" Ready " in nodes_output.stdout'
      retries: 10                # Пробуем 10 раз
      delay: 5                   # Пауза в 5 секунд между попытками
                                 # Это важно, так как K3s нужно время на запуск после установки

    # 6. Настройка доступа для пользователя
    - name: Change permissions of k3s config for gunner
      # По умолчанию конфиг K3s (права доступа к кластеру) закрыт для всех, кроме root.
      # Чтобы ты мог управлять кластером под своим юзером gunner, мы меняем права на чтение.
      file:
        path: /etc/rancher/k3s/k3s.yaml
        mode: '0644'             # Разрешаем чтение всем (для учебного проекта это ок)