name: Build Result

on:
  push:
    branches: [ "main" ]
    # запускать только если изменения в папке result
    paths:
      - 'result/**'

jobs:
  build:
    runs-on: worker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push result
        uses: docker/build-push-action@v5
        with:
          context: ./result
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dos_31onl_dip_result:latest

      - name: Deploy via Ansible
        run: |
          # Используем printf, чтобы точно сохранить все переносы строк ключа
          printf "%s" "${{ secrets.SSH_PRIVATE_KEY }}" > ./deploy_key
          
          # Права доступа
          chmod 600 ./deploy_key
          
          # Запуск
          ansible-playbook -i ansible/inventory.ini deploy_all.yml \
            --private-key ./deploy_key \
            --ssh-common-args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
          
          # Удаление
          rm ./deploy_key