name: Build Result

on:
  push:
    branches: [ "main" ]
    # запускать только если изменения в папке result
    paths:
      - 'result/**'

jobs:
  build:
    runs-on: worker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push result
        uses: docker/build-push-action@v5
        with:
          context: ./result
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dos_31onl_dip_result:latest

      - name: Deploy via Ansible
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # 1. Декодируем и создаем файл ключа
          echo "$SSH_KEY" | base64 -d > ./deploy_key
          chmod 600 ./deploy_key
          
          # 2. Запуск с расширенными параметрами SSH
          ansible-playbook -i ansible/inventory.ini deploy_all.yml \
            -e "ansible_ssh_private_key_file=./deploy_key" \
            --ssh-common-args="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o PubkeyAcceptedAlgorithms=+ssh-ed25519" \
            -vv