name: Test Runner Connection

on:
  workflow_dispatch: # Позволит запустить его кнопкой вручную

jobs:
  check-system:
    runs-on: worker
    steps:
      - name: Who am I
        run: whoami

      - name: Check Docker access
        run: docker ps